version: '3'
services:  
  app:
    container_name: app
    restart: always
    build: .
    ports: 
      - "5001:5001"
    links: 
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    